loggin.level.root=DEBUG
loggin.level.org.hibernate=DEBUG
login.level.org.springframework=DEBUG


spring.datasource.url=jdbc:oracle:thin:@fullstack_tp?TNS_ADMIN=/app/wallet
spring.datasource.username=fullstack1
spring.datasource.password=ClaseDuoc123-
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000


spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

server.port=8080